# Generated by Django 3.0.6 on 2020-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphinx_field', models.TextField(default='')),
                ('other_field', models.TextField(default='')),
                ('attr_float', models.FloatField(default=0.0)),
                ('attr_string', models.CharField(default='', max_length=32)),
                ('attr_bool', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
