# Generated by Django 3.0.6 on 2020-05-08 13:49

from django.db import migrations, models
import django.utils.timezone
import manticore.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphinx_field', manticore.models.fields.RTField(default='')),
                ('other_field', manticore.models.fields.RTField(default='')),
                ('attr_bigint', models.BigIntegerField(default=0)),
                ('attr_bool', models.BooleanField(default=False)),
                ('attr_float', models.FloatField(default=0.0)),
                ('attr_json', manticore.models.fields.JSONField(default={})),
                ('attr_multi_64', manticore.models.fields.BigMultiField(default=[])),
                ('attr_multi', manticore.models.fields.MultiField(default=[])),
                ('attr_string', models.CharField(default='', max_length=32)),
                ('attr_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attr_uint', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
