# Generated by Django 3.0.6 on 2020-05-08 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='attr_bigint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='attr_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='attr_uint',
            field=models.IntegerField(default=0),
        ),
    ]
