# Generated by Django 3.0.6 on 2020-05-08 09:44

from django.db import migrations
import manticore.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200508_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='attr_json',
            field=manticore.models.fields.JSONField(default={}),
        ),
    ]
