# Generated by Django 3.0.6 on 2020-05-08 09:56

from django.db import migrations
import manticore.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_testmodel_attr_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='attr_multi',
            field=manticore.models.fields.MultiField(default=[]),
        ),
    ]
