# Generated by Django 3.0.6 on 2020-05-08 10:01

from django.db import migrations
import manticore.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_testmodel_attr_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='attr_multi_64',
            field=manticore.models.fields.BigMultiField(default=[]),
        ),
    ]
